baseurl: ""
url: "https://wandersonwhcr.github.io"

host: 0.0.0.0
port: 8000

theme_settings:
    title: Wanderson Camargo
    gravatar: e909effb189b69d2363d035ae7b4240d
    description: >
        Programador PHP Zend Framework

    header_text: >
        <p>"Computer Science is no more about computers than Astronomy is about telescopes." — DIJKSTRA, E. W.</p>

    rss: true
    email_address: wandersonwhcr@gmail.com
    bitbucket: wandersonwhcr
    facebook: wandersonwhcr
    github: wandersonwhcr
    linkedin: https://www.linkedin.com/in/wanderson-camargo-82b47797
    twitter: wandersonwhcr

    google_analytics:
    disqus_shortname: wandersonwhcr
    katex: true

    str_follow_on: "Follow on"
    str_rss_follow: "Follow RSS feed"
    str_email: "e-mail"
    str_next: "Próximo"
    str_prev: "Anterior"
    str_continue_reading: "Continue Lendo"

    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
    post_navigation: false

paginate: 5
paginate_path: "blog/page:num"

languages: ['pt-br']
language_data: data.lang.%%

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-paginate
  - jekyll-language-plugin
exclude:
  - Gemfile
  - Gemfile.lock
