baseurl: ""
url: "https://wandersonwhcr.github.io"

theme_settings:
    title: Wanderson Camargo
    gravatar: e909effb189b69d2363d035ae7b4240d
    description: >
        Programador PHP Zend Framework

    header_text: >
        <p>"I do not fear computers. I fear the lack of them." — ASIMOV, L.</p>

    rss: true
    email_address: wandersonwhcr@gmail.com
    github: wandersonwhcr
    linkedin: https://www.linkedin.com/in/wandersonwhcr
    twitter: wandersonwhcr

    google_analytics:
    disqus_shortname: wandersonwhcr
    katex: true

    str_follow_on: "Follow on"
    str_rss_follow: "Follow RSS feed"
    str_email: "e-mail"
    str_next: "Próximo"
    str_prev: "Anterior"
    str_continue_reading: "Continue Lendo"

    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
    post_navigation: false

paginate: 5
paginate_path: "/blog/page-:num/"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
